version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19.03.12
    commands:
      - echo "Docker installation complete."
      - echo "Pulling Checkmarx DAST Docker image..."
      - docker pull checkmarx/dast:latest

  build:
    commands:
      - echo "Starting DAST scan on URL: $TARGET_URL"
      - |
        docker run -e CX_APIKEY=$CX_APIKEY \
        -v $CODEBUILD_SRC_DIR:/demo checkmarx/dast:latest \
        web \
        --environment-id=889259e2-c24b-4dc7-99f5-67009c43e73c \
        --config=/demo/zap_config_web.yaml \
        --base-url=$TARGET_URL \
        --output=/demo/test_output \
        --timeout=10000 \
        --update-interval=10 \
        --jvm-properties=-Xmx3G \
        --log-level=info \
        --verbose \
        --retry=3 \
        --retry-delay=20 \
        --fail-on HIGH

artifacts:
  files:
    - test_output/*
