version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18  # Define la versión de Docker que necesitas
    commands:
      - echo "Instalando la imagen de Checkmarx DAST..."
      - docker pull checkmarx/dast:latest  # Descargar la imagen de Docker

  build:
    commands:
      - echo "Ejecutando el análisis DAST..."
      - docker run -e CX_APIKEY=$CX_APIKEY \  # Usar la variable de entorno para la API Key
          -v $CODEBUILD_SRC_DIR:/demo checkmarx/dast:latest \  # Montar el directorio de trabajo
          web \  # Indicar que se realiza un análisis web
          --environment-id=d8c28879-30b0-4b65-aa74-55a1ab0d4e21 \  # ID de entorno en Checkmarx
          --config=/demo/zap_config_web.yaml \  # Ruta al archivo de configuración
          --base-url=https://us.ast.checkmarx.net/ \  # URL del entorno de Checkmarx
          --output=/demo/test_output \  # Ruta de salida para los resultados
          --timeout=10000 \  # Timeout para la ejecución
          --update-interval=10 \  # Intervalo de actualización
          --jvm-properties=-Xmx3G \  # Configuraciones de JVM
          --log-level=info \  # Nivel de registro
          --verbose \  # Salida detallada
          --retry=3 \  # Número de reintentos en caso de fallo
          --retry-delay=20 \  # Retraso entre reintentos
          --fail-on HIGH  # Fallar si se encuentra un problema crítico

artifacts:
  files:
    - demo/test_output/**  # Incluir todos los archivos de salida en los artefactos
