version: 0.2

phases:
  install:
    commands:
      - echo "Instalando la imagen de Checkmarx DAST..."
      - docker pull checkmarx/dast:latest

  build:
    commands:
      - echo "Ejecutando el análisis DAST..."
      - docker run -e CX_APIKEY=$API_MASTER_KEY -v $CODEBUILD_SRC_DIR:/demo checkmarx/dast:latest web --environment-id=889259e2-c24b-4dc7-99f5-67009c43e73c --config=/demo/zap_config_web.yaml --base-url=https://urlCxOne.com/ --output=/demo/test_output --timeout=10000 --update-interval=10 --jvm-properties=-Xmx3G --log-level=info --verbose --retry=3 --retry-delay=20 --fail-on HIGH

artifacts:
  files:
    - demo/test_output/**
