env:
    contexts:
    -
        excludePaths: []
        includePaths:
        - https://demo.owasp-juice.shop/.*
        name: Default Context
        technology:
            exclude: []
        urls:
        - https://demo.owasp-juice.shop/
    vars: {}
    parameters:
        failOnError: true
        failOnWarning: false
        progressToStdout: true
jobs:
-
    parameters:
        scanOnlyInScope: true
        enableTags: false
    rules: []
    name: passiveScan-config
    type: passiveScan-config
-
    parameters: null
    context: Default Context
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
    name: spider
    type: spider
-
    parameters: null
    context: Default Context
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 1
    runOnlyIfModern: false
    name: spiderAjax
    type: spiderAjax
-
    parameters: {}
    name: passiveScan-wait
    type: passiveScan-wait
-
    parameters:
        context: Default Context
    policyDefinition:
        rules: []
    name: activeScan
    type: activeScan
-
    parameters: null
    template: traditional-pdf
    reportDir: ''
    reportTitle: ZAP Scanning Report
    reportDescription: ''
    name: report-pdf
    type: report
